export const SEED_IMPLEMENTING_PARTNERS = [
    {
        name_en: 'Najd Education Alliance',
        name_ar: 'تحالف نجد التعليمي',
        logo: 'NE',
        sector: 'التعليم',
        status: 'نشط',
        country: 'Saudi Arabia',
        city: 'Riyadh',
        description: 'Delivers remedial learning, teacher coaching, and digital classroom support for underserved public schools across central Saudi Arabia.',
        phone: '+966 11 482 1900',
        email: 'partnerships@najdalliance.org',
        website: 'https://www.najdalliance.org',
        address: 'King Abdullah Road, Al Wurud District, Riyadh 12253',
        coordinates: { lat: 24.7136, lng: 46.6753 },
        rating: '4.8',
        budget: '1450000',
        projects_completed: 19,
        projects_in_progress: 4,
        contacts: [
            {
                id: 'nea-contact-1',
                name: 'Maha Al-Harbi',
                position: 'Partnerships Director',
                email: 'maha.alharbi@najdalliance.org',
                phone: '+966 50 221 8841',
                whatsapp: '+966 50 221 8841',
                isPrimary: true,
                photoUrl: '',
            },
            {
                id: 'nea-contact-2',
                name: 'Omar Al-Mutairi',
                position: 'Programs Manager',
                email: 'omar.m@najdalliance.org',
                phone: '+966 55 301 7722',
                whatsapp: '+966 55 301 7722',
                isPrimary: false,
                photoUrl: '',
            },
        ],
        custom_fields: {
            founded_year: 2014,
            registration_number: 'KSA-NGO-EDU-2147',
            legal_type: 'Non-profit association',
            staff_count: 37,
            volunteer_count: 120,
            service_areas: ['Riyadh', 'Qassim', 'Hail'],
            focus_areas: ['Remedial education', 'Teacher development', 'STEM labs', 'School leadership'],
            target_groups: ['Primary students', 'Lower secondary students', 'Teachers'],
            languages_supported: ['Arabic', 'English'],
            agreement_status: 'Active through 2027-08-31',
            due_diligence_status: 'Approved',
            last_assessment_date: '2025-11-10',
        },
    },
    {
        name_en: 'Blue Crescent Medical Relief',
        name_ar: 'الهلال الأزرق للإغاثة الطبية',
        logo: 'BC',
        sector: 'الصحة',
        status: 'نشط',
        country: 'Jordan',
        city: 'Amman',
        description: 'Operates mobile clinics, prosthetics referrals, and maternal health outreach for refugee and low-income communities in Jordan.',
        phone: '+962 6 566 4201',
        email: 'coordination@bluecrescentmed.org',
        website: 'https://www.bluecrescentmed.org',
        address: 'Mecca Street, Building 91, Amman 11118',
        coordinates: { lat: 31.9539, lng: 35.9106 },
        rating: '4.6',
        budget: '980000',
        projects_completed: 26,
        projects_in_progress: 6,
        contacts: [
            {
                id: 'bcmr-contact-1',
                name: 'Dr. Lina Haddad',
                position: 'Executive Director',
                email: 'lina.haddad@bluecrescentmed.org',
                phone: '+962 79 810 5511',
                whatsapp: '+962 79 810 5511',
                isPrimary: true,
                photoUrl: '',
            },
            {
                id: 'bcmr-contact-2',
                name: 'Fadi Nasser',
                position: 'Field Operations Lead',
                email: 'fadi.nasser@bluecrescentmed.org',
                phone: '+962 79 455 1020',
                whatsapp: '+962 79 455 1020',
                isPrimary: false,
                photoUrl: '',
            },
        ],
        custom_fields: {
            founded_year: 2011,
            registration_number: 'JOR-HEALTH-7783',
            legal_type: 'Medical relief NGO',
            staff_count: 54,
            volunteer_count: 86,
            service_areas: ['Amman', 'Mafraq', 'Irbid', 'Zarqa'],
            focus_areas: ['Mobile clinics', 'Maternal health', 'Chronic disease screening', 'Rehabilitation referrals'],
            target_groups: ['Refugees', 'Women', 'Children', 'Elderly'],
            languages_supported: ['Arabic', 'English'],
            agreement_status: 'Active through 2026-12-31',
            due_diligence_status: 'Approved with annual review',
            medical_licenses_verified: true,
            last_assessment_date: '2026-01-18',
        },
    },
    {
        name_en: 'Nile Shelter Response Network',
        name_ar: 'شبكة النيل للاستجابة للإيواء',
        logo: 'NS',
        sector: 'الإغاثة',
        status: 'قيد المراجعة',
        country: 'Egypt',
        city: 'Cairo',
        description: 'Provides emergency shelter kits, winterization support, and temporary accommodation coordination during rapid-onset crises.',
        phone: '+20 2 2418 6300',
        email: 'grants@nileshelter.org',
        website: 'https://www.nileshelter.org',
        address: 'Nasr City, Cairo Governorate 11765',
        coordinates: { lat: 30.0444, lng: 31.2357 },
        rating: '4.1',
        budget: '720000',
        projects_completed: 11,
        projects_in_progress: 3,
        contacts: [
            {
                id: 'nsrn-contact-1',
                name: 'Hossam El-Din',
                position: 'Partnership Manager',
                email: 'hossam.eldin@nileshelter.org',
                phone: '+20 100 311 4210',
                whatsapp: '+20 100 311 4210',
                isPrimary: true,
                photoUrl: '',
            },
            {
                id: 'nsrn-contact-2',
                name: 'Reem Tarek',
                position: 'Emergency Response Coordinator',
                email: 'reem.tarek@nileshelter.org',
                phone: '+20 109 655 7822',
                whatsapp: '+20 109 655 7822',
                isPrimary: false,
                photoUrl: '',
            },
        ],
        custom_fields: {
            founded_year: 2018,
            registration_number: 'EG-RELIEF-4412',
            legal_type: 'Relief consortium',
            staff_count: 22,
            volunteer_count: 210,
            service_areas: ['Cairo', 'Alexandria', 'Asyut'],
            focus_areas: ['Shelter kits', 'Winterization', 'Rapid needs assessment', 'NFI distribution'],
            target_groups: ['Displaced families', 'Crisis-affected households'],
            languages_supported: ['Arabic', 'English'],
            agreement_status: 'Due diligence in progress',
            due_diligence_status: 'Financial review pending',
            flagged_risks: ['Procurement policy update requested', 'Board minutes missing for FY2025'],
            last_assessment_date: '2026-02-04',
        },
    },
    {
        name_en: 'Green Horizons Cooperative',
        name_ar: 'تعاونية الآفاق الخضراء',
        logo: 'GH',
        sector: 'البيئة',
        status: 'نشط',
        country: 'Morocco',
        city: 'Rabat',
        description: 'Leads climate-smart agriculture, water harvesting, and community reforestation initiatives with women-led rural cooperatives.',
        phone: '+212 537 72 4180',
        email: 'alliances@greenhorizons.ma',
        website: 'https://www.greenhorizons.ma',
        address: 'Avenue Annakhil, Hay Riad, Rabat 10100',
        coordinates: { lat: 34.0209, lng: -6.8416 },
        rating: '4.7',
        budget: '1135000',
        projects_completed: 14,
        projects_in_progress: 5,
        contacts: [
            {
                id: 'ghc-contact-1',
                name: 'Salma Benjelloun',
                position: 'Regional Partnerships Lead',
                email: 'salma.benjelloun@greenhorizons.ma',
                phone: '+212 661 904 772',
                whatsapp: '+212 661 904 772',
                isPrimary: true,
                photoUrl: '',
            },
            {
                id: 'ghc-contact-2',
                name: 'Yassine El Idrissi',
                position: 'Monitoring and Learning Officer',
                email: 'yassine.idrissi@greenhorizons.ma',
                phone: '+212 662 119 305',
                whatsapp: '+212 662 119 305',
                isPrimary: false,
                photoUrl: '',
            },
        ],
        custom_fields: {
            founded_year: 2016,
            registration_number: 'MA-ENV-3021',
            legal_type: 'Cooperative federation',
            staff_count: 31,
            volunteer_count: 64,
            service_areas: ['Rabat-Sale-Kenitra', 'Beni Mellal-Khenifra', 'Souss-Massa'],
            focus_areas: ['Reforestation', 'Water harvesting', 'Climate-smart agriculture', 'Community livelihoods'],
            target_groups: ['Women farmers', 'Rural youth', 'Village associations'],
            languages_supported: ['Arabic', 'French', 'English'],
            agreement_status: 'Active through 2028-03-31',
            due_diligence_status: 'Approved',
            esg_score: 91,
            last_assessment_date: '2025-12-02',
        },
    },
    {
        name_en: 'Anatolia Community Development Forum',
        name_ar: 'منتدى الأناضول للتنمية المجتمعية',
        logo: 'AC',
        sector: 'التنمية',
        status: 'غير نشط',
        country: 'Turkey',
        city: 'Gaziantep',
        description: 'Previously supported livelihoods, vocational training, and SME incubation for host and displaced communities in southeast Turkey.',
        phone: '+90 342 211 5600',
        email: 'info@anatoliaforum.org',
        website: 'https://www.anatoliaforum.org',
        address: 'Incilipinar Mah. 36001 Nolu Cad., Gaziantep 27090',
        coordinates: { lat: 37.0662, lng: 37.3833 },
        rating: '3.7',
        budget: '640000',
        projects_completed: 23,
        projects_in_progress: 0,
        contacts: [
            {
                id: 'acdf-contact-1',
                name: 'Emre Kaya',
                position: 'Former Partnership Focal Point',
                email: 'emre.kaya@anatoliaforum.org',
                phone: '+90 532 440 1881',
                whatsapp: '+90 532 440 1881',
                isPrimary: true,
                photoUrl: '',
            },
            {
                id: 'acdf-contact-2',
                name: 'Rana Al-Hassan',
                position: 'Programs Advisor',
                email: 'rana.hassan@anatoliaforum.org',
                phone: '+90 533 672 2440',
                whatsapp: '+90 533 672 2440',
                isPrimary: false,
                photoUrl: '',
            },
        ],
        custom_fields: {
            founded_year: 2013,
            registration_number: 'TR-DEV-1884',
            legal_type: 'Community development NGO',
            staff_count: 18,
            volunteer_count: 40,
            service_areas: ['Gaziantep', 'Sanliurfa', 'Hatay'],
            focus_areas: ['Livelihoods', 'Vocational training', 'Small business incubation', 'Cash-for-work'],
            target_groups: ['Youth', 'Women', 'Refugee entrepreneurs'],
            languages_supported: ['Turkish', 'Arabic', 'English'],
            agreement_status: 'Expired on 2025-06-30',
            due_diligence_status: 'Dormant partner',
            inactive_reason: 'Closed regional office after grant portfolio ended',
            last_assessment_date: '2025-05-12',
        },
    },
] as const;
