import type { stakeholders } from './schema';

type StakeholderInsert = typeof stakeholders.$inferInsert;

/** All user-facing text fields are Arabic script (name, country, phone, needs, insights). */
export const SEED_STAKEHOLDER_ARABIC_ONLY: StakeholderInsert = {
    name_en: '',
    name_ar: 'جمعية التنمية المجتمعية الكويتية',
    type: 'community',
    category: 'foundation',
    status: 'active',
    classification: 'primary',
    email: '',
    phone: '٢٢٢٢ ١١١١',
    country: 'الكويت',
    health_score: 91,
    engagement_score: 88,
    relationship_level: 'core',
    risk_level: 'low',
    risk_profile: 'supporter',
    power: 45,
    interest: 82,
    ai_insights: 'علاقة ممتازة مع الجهة — يُنصح بمتابعة ربع سنوية',
    last_contact: new Date('2024-07-12T09:00:00Z'),
    needs: ['تقارير الأثر', 'الشفافية المالية', 'بيانات المستفيدين'],
    custom_fields: { seed_locale: 'ar-only' },
};

export const SEED_STAKEHOLDERS: Omit<StakeholderInsert, 'org_id'>[] = [
    SEED_STAKEHOLDER_ARABIC_ONLY,
    {
        name_en: 'Global Charity Foundation',
        name_ar: 'مؤسسة الخير العالمية',
        type: 'donor',
        category: 'foundation',
        status: 'active',
        classification: 'primary',
        email: 'contact@gcf.org',
        phone: '+1-202-555-0104',
        country: 'USA',
        health_score: 95,
        engagement_score: 92,
        relationship_level: 'strategic',
        risk_level: 'low',
        risk_profile: 'supporter',
        power: 90,
        interest: 85,
        ai_insights: 'stakeholder_management.insights.excellent_relation',
        last_contact: new Date('2024-07-15T10:00:00Z'),
        needs: ['Impact Reports', 'Financial Transparency'],
        total_donations: '1200000',
    },
    {
        name_en: 'Ahmed Al-Kareem Family',
        name_ar: 'عائلة أحمد الكريم',
        type: 'beneficiary',
        category: 'family',
        status: 'active',
        classification: 'primary',
        email: 'ahmed.kareem@family.com',
        phone: '+966 50 111 2222',
        country: 'Saudi Arabia',
        health_score: 88,
        engagement_score: 85,
        relationship_level: 'core',
        risk_level: 'low',
        risk_profile: 'supporter',
        power: 20,
        interest: 90,
        ai_insights: 'stakeholder_management.insights.active_beneficiary',
        last_contact: new Date('2024-07-20T14:00:00Z'),
        needs: ['Timely Support', 'Clear Communication'],
        support_received: '5000',
    },
    {
        name_en: 'Advanced Tech Company',
        name_ar: 'شركة التقنية المتطورة',
        type: 'partner',
        category: 'company',
        status: 'active',
        classification: 'secondary',
        email: 'partners@adv-tech.com',
        phone: '+90 212 555 0100',
        country: 'Turkey',
        health_score: 78,
        engagement_score: 65,
        relationship_level: 'important',
        risk_level: 'medium',
        risk_profile: 'neutral',
        power: 70,
        interest: 40,
        ai_insights: 'stakeholder_management.insights.warning_communication',
        last_contact: new Date('2024-06-28T09:00:00Z'),
        needs: ['Joint PR Opportunities', 'Clear KPIs'],
        partnership_value: '75000',
    },
    {
        name_en: 'Ministry of Awqaf and Islamic Affairs',
        name_ar: 'وزارة الأوقاف والشئون الإسلامية',
        type: 'government',
        category: 'company',
        status: 'active',
        classification: 'primary',
        email: 'info@awqaf.gov.kw',
        phone: 'N/A',
        country: 'Kuwait',
        health_score: 88,
        engagement_score: 85,
        relationship_level: 'strategic',
        risk_level: 'low',
        risk_profile: 'supporter',
        power: 92,
        interest: 88,
        ai_insights: 'stakeholder_management.insights.newly_added',
        last_contact: new Date('2024-05-20T10:00:00Z'),
        needs: ['Sharia Compliance', 'Zakat Distribution Reports'],
    },
    {
        name_en: 'Mr. Abdullah Al-Jaber',
        name_ar: 'السيد عبد الله الجابر',
        type: 'board_member',
        category: 'family',
        status: 'active',
        classification: 'primary',
        email: 'a.aljaber@board.org',
        phone: '+965 9988 7766',
        country: 'Kuwait',
        health_score: 98,
        engagement_score: 99,
        relationship_level: 'strategic',
        risk_level: 'low',
        risk_profile: 'supporter',
        power: 100,
        interest: 100,
        ai_insights: 'stakeholder_management.insights.board_chairman',
        last_contact: new Date('2024-07-23T18:00:00Z'),
        needs: ['Strategic Reports', 'Board Meeting Agendas'],
    },
];
